const VERSION = '1.0.0'

const {
  NODE_ENV,
  LOG_LEVEL,
  PORT,
  SANDBOX,
  ALLOWED_CORS_ORIGINS,
  WHITELISTED_CORS_DOMAINS,
  FALLBACK_CORS_ORIGIN,
  TWITTER_CONSUMER_API_KEY,
  TWITTER_CONSUMER_API_SECRET,
  TWITTER_ACCESS_TOKEN,
  TWITTER_ACCESS_SECRET,
  GRAPH_URL,
  MONGODB_CONNECTION_STRING,
  RECEIPT_URL
} = process.env

export {
  NODE_ENV,
  VERSION,
  LOG_LEVEL,
  PORT,
  SANDBOX,
  ALLOWED_CORS_ORIGINS,
  WHITELISTED_CORS_DOMAINS,
  FALLBACK_CORS_ORIGIN,
  TWITTER_CONSUMER_API_KEY,
  TWITTER_CONSUMER_API_SECRET,
  TWITTER_ACCESS_TOKEN,
  TWITTER_ACCESS_SECRET,
  GRAPH_URL,
  MONGODB_CONNECTION_STRING,
  RECEIPT_URL
}
